@url = http://localhost:8000
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjg0NTYsImVtYWlsIjoiYWRtaW5AZWV4YW1wbGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUzMjc0MDI3LCJleHAiOjE3NTMyNzU4Mjd9.H00eF3khZvmEFZReu5EA2AbUJsg6tTzFB-vpH0KrN5k

### Get all users
GET {{url}}//driver/by-user/8457
Authorization: Bearer {{access_token}}

### Get user by ID
GET {{url}}/user/1
Authorization: Bearer {{access_token}}

### Create a user
POST {{url}}/user
Content-Type: application/json
Authorization: Bearer {{access_token}}
{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "phone": "1234567890",
  "password": "password123",
  "role": "customer"
}

### Update a user
PATCH {{url}}/user/1
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Doe"
}

### Delete a user
DELETE {{url}}/user/1
Authorization: Bearer {{access_token}}

### Get all bookings
GET {{url}}/bookings
Authorization: Bearer {{access_token}}

### Get booking by ID
GET {{url}}/bookings/1
Authorization: Bearer {{access_token}}

### Create a booking
POST {{url}}/bookings
Content-Type: application/json

{
  "start_latitude": 49.41461,
  "start_longitude": 8.681495,
  "end_latitude": 49.420318,
  "end_longitude": 8.687872,
  "pickup_time": "2025-07-02T19:00:00.000Z",
  "dropoff_time": "2025-07-02T20:00:00.000Z"
}

### Update a booking
PATCH {{url}}/bookings/1
Content-Type: application/json
Authorization: Bearer {{access_token}}
{
  "status": "Completed"
}

### Delete a booking
DELETE {{url}}/bookings/1
Authorization: Bearer {{access_token}}